//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Step6502.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDS_MEMORY_NAME                 126
#define IDS_CODE_VIEW                   127
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDS_STRING_STRING               129
#define IDS_STRING130                   130
#define IDS_MEMORY2_NAME                130
#define IDS_GRAPHIC_VIEW                131
#define IDS_BREAKPOINTS                 132
#define IDS_WATCH                       133
#define IDS_VICE_MONITOR                134
#define ID_VIEW_OUTPUTWND               149
#define IDS_OUTPUT_WND                  157
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDR_OUTPUT_POPUP                182
#define ID_VIEW_REGISTERS               183
#define IDS_REGISTERS_WND               184
#define ID_VIEW_MEMORY                  185
#define ID_BUTTON_STOP                  186
#define ID_BUTTON_GO                    187
#define ID_BUTTON_REVERSE               188
#define ID_BUTTON_STEP                  189
#define ID_BUTTON_STEP_BACK             190
#define ID_VIEW_MEMORY2                 191
#define ID_VIEW_CODE                    192
#define ID_BUTTON_FONTSIZE              193
#define ID_VIEW_GRAPHIC                 194
#define ID_GRAPHIC_STYLE_FIELD          195
#define ID_ASSEMBLE_INPUT               197
#define ID_MEMORY_ADDRESS_FIELD         198
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define ID_GRAPHIC_ADDRESS_FIELD        220
#define ID_GRAPHIC_WIDTH_FIELD          221
#define ID_GRAPHIC_HEIGHT_FIELD         222
#define ID_GRAPHIC_FONT_FIELD           223
#define ID_MEMORY_COLUMNS_FIELD         228
#define ID_BREAKPOINTS                  229
#define ID_BREAKPOINT_LIST              230
#define ID_BREAKPOINT_EDIT              231
#define ID_WATCH_VIEW                   232
#define ID_WATCH_LIST                   233
#define ID_WATCH_EDIT                   234
#define ID_VICE_MONITOR                 235
#define ID_VICE_EDIT					236
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EDIT_MENU                   306
#define IDB_BREAKPOINT                  314
#define IDB_BITMAP1                     316
#define IDB_PC_ARROW                    316
#define IDD_LOAD_ADDRESS                324
#define IDI_ICON1                       326
#define IDI_DROP_ICON                   326
#define IDI_ICON2                       327
#define IDI_BREAKPOINT_ICON             327
#define IDC_EDIT1                       1000
#define IDC_LOAD_ADDRESS_EDIT_MANUAL    1000
#define IDC_LIST1                       1002
#define IDC_FILETYPE_PRG                1008
#define IDC_FILETYPE_A2B                1009
#define IDC_FILETYPE_BIN                1010
#define IDC_FILETYPE_GROUP              1011
#define IDC_CHECK1                      1013
#define IDC_SET_PC_TO_LOAD_ADDRESS      1013
#define IDC_RESET_UNDO                  1013
#define IDC_FORCE_ADDRESS_CHECK         1014
#define IDC_RELOAD_NOTE                 1015
#define IDC_RELOAD_NOTE_TEXT            1016
#define IDC_SET_PC_TO_LOAD_ADDRESS2     1017
#define IDC_GROUP_LOAD_OPTIONS          1018
#define ID_BUTTON_BREAK                 32782
#define ID_LOAD_ADDRESS_PRG             32783
#define ID_BUTTON_IRQ                   32784
#define ID_LOAD_ADDRESS_TEXT            32785
#define ID_BUTTON_NMI                   32786
#define ID_BUTTON_RESET                 32787
#define ID_BUTTON_RELOAD                32788
#define ID_BUTTON_LOAD                  32794
#define ID_VIEW_FONTSIZE                32796
#define ID_FONTSIZE_12                  32797
#define ID_LOAD_ADDRESS_A2B             32798
#define ID_FONTSIZE_14                  32798
#define ID_LOAD_ADDRESS_ASK             32799
#define ID_FONTSIZE_16                  32799
#define ID_FONTSIZE_18                  32800
#define ID_FONTSIZE_20                  32801
#define ID_FONTSIZE_22                  32802
#define ID_FONTSIZE_24                  32803
#define ID_BUTTON_VICE                  32805
#define ID_BUTTON32806                  32806

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        328
#define _APS_NEXT_COMMAND_VALUE         32807
#define _APS_NEXT_CONTROL_VALUE         1019
#define _APS_NEXT_SYMED_VALUE           311
#endif
#endif
